"""Reading a session transcript into a timeline.

The transcript belongs to Claude Code, not to us -- its shape is observed, so
these tests fix the shapes we rely on and the behaviour when they are absent.
"""
import json
import os

import pytest

from claudlet.core import transcript as T


def _line(**rec):
    return json.dumps(rec)


def _user(text):
    return _line(type="user", message={"role": "user", "content": text})


def _assistant(*blocks):
    return _line(type="assistant",
                 message={"role": "assistant", "content": list(blocks)})


def _tool(name, **data):
    return {"type": "tool_use", "name": name, "input": data}


# ---- parsing ----

def test_a_user_prompt_is_captured():
    out = T.parse([_user("what is this?")])
    assert out == [{"kind": T.USER, "ts": None, "text": "what is this?"}]


def test_an_assistant_reply_is_captured():
    out = T.parse([_assistant({"type": "text", "text": "here you go"})])
    assert out[0]["kind"] == T.AGENT and out[0]["text"] == "here you go"


def test_a_tool_call_is_captured():
    out = T.parse([_assistant(_tool("Bash", description="List files"))])
    assert out[0]["kind"] == T.TOOL
    assert out[0]["name"] == "Bash" and out[0]["detail"] == "List files"


def test_a_reply_and_its_tool_calls_both_appear():
    out = T.parse([_assistant({"type": "text", "text": "running it"},
                              _tool("Bash", description="do the thing"))])
    assert [e["kind"] for e in out] == [T.AGENT, T.TOOL]


def test_a_description_is_preferred_over_the_raw_command():
    out = T.parse([_assistant(_tool("Bash", command="ls -la", description="List"))])
    assert out[0]["detail"] == "List"


def test_a_command_stands_in_when_there_is_no_description():
    out = T.parse([_assistant(_tool("Bash", command="ls -la /tmp"))])
    assert out[0]["detail"] == "ls -la /tmp"


def test_env_assignments_are_trimmed_off_a_command():
    """Without this every such row reads as the same long path prefix."""
    out = T.parse([_assistant(_tool("Bash", command="SP=/tmp/x M=/y grep -n foo"))])
    assert out[0]["detail"] == "grep -n foo"


def test_other_tools_are_summarised_by_their_own_field():
    out = T.parse([_assistant(_tool("Read", file_path="/tmp/x.py"))])
    assert out[0]["detail"] == "/tmp/x.py"


def test_a_todo_list_becomes_a_task_entry():
    out = T.parse([_assistant(_tool("TodoWrite", todos=[
        {"content": "first", "status": "completed"},
        {"content": "second", "status": "in_progress"}]))])
    assert out[0]["kind"] == T.TODO
    assert [i["text"] for i in out[0]["items"]] == ["first", "second"]
    assert out[0]["items"][0]["status"] == "completed"


def test_an_empty_todo_list_is_skipped():
    assert T.parse([_assistant(_tool("TodoWrite", todos=[]))]) == []


def test_command_wrappers_are_not_shown_as_user_speech():
    noisy = ["<command-name>foo</command-name>",
             "<local-command-stdout>out</local-command-stdout>",
             "Caveat: The messages below were generated by the user"]
    assert T.parse([_user(n) for n in noisy]) == []


def test_blank_prompts_are_skipped():
    assert T.parse([_user("   ")]) == []


def test_unknown_record_types_are_skipped():
    assert T.parse([_line(type="file-history-snapshot", message={})]) == []


def test_malformed_lines_cost_one_entry_not_the_read():
    out = T.parse([_user("kept"), "{not json", _user("also kept")])
    assert [e["text"] for e in out] == ["kept", "also kept"]


def test_a_record_without_a_message_is_skipped():
    assert T.parse([_line(type="user")]) == []


def test_blank_lines_are_skipped():
    assert T.parse(["", "   ", _user("kept")])[0]["text"] == "kept"


def test_content_blocks_are_flattened_to_text():
    out = T.parse([_line(type="user", message={"role": "user", "content": [
        {"type": "text", "text": "part one"},
        {"type": "text", "text": "part two"}]})])
    assert "part one" in out[0]["text"] and "part two" in out[0]["text"]


def test_very_long_text_is_clipped():
    out = T.parse([_user("x" * (T.MAX_TEXT * 3))])
    assert len(out[0]["text"]) <= T.MAX_TEXT + 2


def test_the_timeline_is_capped():
    out = T.parse([_user("q%d" % i) for i in range(T.MAX_ENTRIES + 50)])
    assert len(out) == T.MAX_ENTRIES


def test_the_cap_keeps_the_most_recent():
    out = T.parse([_user("q%d" % i) for i in range(T.MAX_ENTRIES + 5)])
    assert out[-1]["text"] == "q%d" % (T.MAX_ENTRIES + 4)


# ---- locating the file ----

def test_a_profile_root_is_searched_before_the_default(monkeypatch):
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "/profiles/dev")
    roots = T.transcript_roots()
    assert roots[0].startswith("/profiles/dev")


def test_the_default_root_is_always_included(monkeypatch):
    monkeypatch.delenv("CLAUDE_CONFIG_DIR", raising=False)
    assert any(".claude/projects" in r for r in T.transcript_roots())


def test_a_transcript_is_found_by_session_id(tmp_path):
    proj = tmp_path / "some-project"
    proj.mkdir()
    (proj / "abc-123.jsonl").write_text(_user("hi"))
    assert T.find_transcript("abc-123", [str(tmp_path)])


def test_an_unknown_session_finds_nothing(tmp_path):
    assert T.find_transcript("nope", [str(tmp_path)]) is None


def test_no_session_id_finds_nothing():
    assert T.find_transcript(None) is None


def test_load_reads_the_found_file(tmp_path):
    proj = tmp_path / "p"
    proj.mkdir()
    (proj / "s1.jsonl").write_text(_user("hello") + "\n")
    assert T.load("s1", [str(tmp_path)])[0]["text"] == "hello"


def test_load_of_a_missing_transcript_is_empty():
    assert T.load("nothing-here", ["/no/such/root"]) == []


# ---- rendering ----

def test_an_empty_timeline_renders_a_message():
    assert "찾지 못했" in T.render_html([])


def test_each_kind_is_labelled():
    html = T.render_html([{"kind": T.USER, "text": "asked"},
                          {"kind": T.AGENT, "text": "replied"},
                          {"kind": T.TOOL, "name": "Bash", "detail": "ls"}])
    assert "asked" in html and "replied" in html and "Bash" in html


def test_a_completed_task_is_struck_through():
    html = T.render_html([{"kind": T.TODO,
                           "items": [{"text": "done", "status": "completed"}]}])
    assert "line-through" in html


def test_markup_in_a_prompt_cannot_reach_the_page():
    """Prompts and file contents are full of angle brackets -- data, not markup."""
    html = T.render_html([{"kind": T.USER, "text": "<script>x</script> & more"}])
    assert "<script>" not in html and "&lt;script&gt;" in html


def test_markup_in_a_tool_detail_is_escaped():
    html = T.render_html([{"kind": T.TOOL, "name": "Bash",
                           "detail": "grep '<b>' file"}])
    assert "<b>" not in html.replace("<b>Bash</b>", "")
